baseURL = "https://huangno1.github.io/"
languageCode = "zh-tw"
title = "Rem Blog"
# theme = "AllinOne"
builddrafts                = false
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  # [[menu.main]]
  #   name                   = "Moment"
  #   weight                 = -110
  #   identifier             = "moment"
  #   url                    = "moment/" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  


[params]
  faviconfile              = "img/zheng.png"               # from static/
  avatar                   = "img/profile.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Rem"
  description              = ["love programming.", "An engineer by the interest.", "I will always share my stories and create new stories with everyone.", "While there is life, there is hope.", "Hang on to your dreams."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "When times become difficult (and you know they sometimes will), remember a moment in your life that was filled with joy and happiness.Remember how it made you feel, and you will have the strength you need to get through any trial."

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "fh831.cp9gw@email.com"
  github                   = "//github.com/HuangNO1"
#   linkedin                 = "//linkedin.com/in/you"
  facebook                 = "//facebook.com/myRem"
#   googleplus               = "//google.com/you"
  twitter                  = "//twitter.com/Rem59881439" 
#   px500                    = "//px500"
#   instagram                = "//instagram.com/you"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "UA-138697151-2"
    
    
